# IF THE PLUGIN IS OUTDATED A NEW CONFIG.YML WILL BE CREATED, REMOVING ALL PREVIOUS EDITS TO THIS FILE.
#
# -----
#
# Allows night to be skipped instantly by one player sleeping.
#
# allow-night-skip: true
#
# -----
#
# Helps config.yml update. DO NOT CHANGE.
#
# version: 1.0
allow-night-skip: true
version: 1.0