# IF THE PLUGIN IS OUTDATED A NEW CONFIG.YML WILL BE CREATED, REMOVING ALL PREVIOUS EDITS TO THIS FILE.
display-server-name: true
display-server-deaths: true
custom-server-name: Whomst'd've Minecraft Server
version: 1.3