name: DeathDisplay
main: com.servebeer.quake.Main
version: 1.3
commands:
  ddhelp:
    description: Displays a list of commands
    usage: /<command>
    permission: DeathDisplay.help
    
  ddcfg:
    description: Allows editing of the cfg from in-game
    usage: /<command> [ displayname | displaydeaths | servername ]
    permission: DeathDisplay.cfg